-- 006_phase2_trials_and_reports.sql
-- Aheka Hyperlocal Platform Phase 2: 30-Day Free Trials, Conversion & Performance Reporting

-- 1. Enums
DO $$ BEGIN
  CREATE TYPE trial_status AS ENUM ('active', 'expired', 'converted', 'cancelled');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- 2. Listing Trials Table
-- The commercial unit is: 1 Vendor + 1 Category + 1 Taluka = 1 Listing
-- Each listing can have trial records.
CREATE TABLE IF NOT EXISTS listing_trials (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  vendor_listing_id UUID NOT NULL REFERENCES vendor_listings(id) ON DELETE CASCADE,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  status trial_status NOT NULL DEFAULT 'active',
  converted_at TIMESTAMPTZ,
  converted_subscription_id UUID REFERENCES subscriptions(id) ON DELETE SET NULL,
  is_override BOOLEAN NOT NULL DEFAULT false,
  override_reason TEXT,
  created_by UUID REFERENCES app_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Vendor Report Snapshots Table
-- Records official performance report snapshots generated by Admin at renewal/conversion.
CREATE TABLE IF NOT EXISTS vendor_report_snapshots (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  vendor_id UUID NOT NULL REFERENCES vendors(id) ON DELETE CASCADE,
  vendor_listing_id UUID REFERENCES vendor_listings(id) ON DELETE SET NULL,
  from_date TIMESTAMPTZ NOT NULL,
  to_date TIMESTAMPTZ NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  report_type VARCHAR(50) NOT NULL DEFAULT 'listing', -- 'listing' or 'combined_vendor'
  metrics_json JSONB NOT NULL,
  notes TEXT,
  created_by UUID REFERENCES app_users(id) ON DELETE SET NULL
);

-- 4. Strategic Indexes
CREATE INDEX IF NOT EXISTS idx_listing_trials_lookup 
  ON listing_trials(vendor_listing_id, status, starts_at, ends_at);

CREATE INDEX IF NOT EXISTS idx_analytics_events_listing 
  ON analytics_events(vendor_listing_id, event_type, occurred_at);

CREATE INDEX IF NOT EXISTS idx_report_snapshots_vendor 
  ON vendor_report_snapshots(vendor_id, generated_at);

-- 5. Row Level Security Policies
ALTER TABLE listing_trials ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendor_report_snapshots ENABLE ROW LEVEL SECURITY;

-- Admins have full access to listing_trials
CREATE POLICY admin_all_listing_trials ON listing_trials
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM app_users
      WHERE app_users.auth_user_id = auth.uid()
        AND app_users.role = 'admin'
        AND app_users.is_active = true
    )
  );

-- Vendors can view trials for their own listings
CREATE POLICY vendor_read_own_listing_trials ON listing_trials
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM vendor_listings vl
      JOIN app_users au ON au.vendor_id = vl.vendor_id
      WHERE vl.id = listing_trials.vendor_listing_id
        AND au.auth_user_id = auth.uid()
        AND au.is_active = true
    )
  );

-- Admins have full access to report snapshots
CREATE POLICY admin_all_report_snapshots ON vendor_report_snapshots
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM app_users
      WHERE app_users.auth_user_id = auth.uid()
        AND app_users.role = 'admin'
        AND app_users.is_active = true
    )
  );

-- Vendors can view report snapshots for their own vendor profile
CREATE POLICY vendor_read_own_snapshots ON vendor_report_snapshots
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM app_users au
      WHERE au.vendor_id = vendor_report_snapshots.vendor_id
        AND au.auth_user_id = auth.uid()
        AND au.is_active = true
    )
  );

-- 6. Stored Procedure: Start 30-Day Free Trial
-- Enforces:
-- a) 10-slot limit across both active trial and paid listings in taluka + category
-- b) One free trial per listing anti-abuse rule (unless overridden with reason)
-- c) Exactly 30-day IST period calculation
CREATE OR REPLACE FUNCTION start_listing_trial(
  p_listing_id UUID,
  p_start_date TIMESTAMPTZ DEFAULT NOW(),
  p_is_override BOOLEAN DEFAULT false,
  p_override_reason TEXT DEFAULT NULL,
  p_admin_user_id UUID DEFAULT NULL
)
RETURNS JSONB AS $$
DECLARE
  v_listing RECORD;
  v_max_slots INTEGER;
  v_active_count INTEGER;
  v_existing_trials_count INTEGER;
  v_starts_at TIMESTAMPTZ;
  v_ends_at TIMESTAMPTZ;
  v_trial_id UUID;
BEGIN
  -- Lock listing record
  SELECT vl.*, v.provider_name, v.approval_status AS vendor_status, v.is_suspended
  INTO v_listing
  FROM vendor_listings vl
  JOIN vendors v ON v.id = vl.vendor_id
  WHERE vl.id = p_listing_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Listing not found');
  END IF;

  IF v_listing.vendor_status != 'approved' OR v_listing.is_suspended = true THEN
    RETURN jsonb_build_object('success', false, 'error', 'Vendor is not in approved active status');
  END IF;

  -- Anti-abuse check: one free trial per listing rule
  SELECT COUNT(*) INTO v_existing_trials_count
  FROM listing_trials
  WHERE vendor_listing_id = p_listing_id
    AND status IN ('active', 'expired', 'converted');

  IF v_existing_trials_count > 0 AND NOT p_is_override THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'TRIAL_ALREADY_USED',
      'message', 'A free trial has already been used for this listing. Admin override required with reason.'
    );
  END IF;

  IF p_is_override AND (p_override_reason IS NULL OR TRIM(p_override_reason) = '') THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'OVERRIDE_REASON_REQUIRED',
      'message', 'Admin override reason is required when granting an additional trial.'
    );
  END IF;

  -- Read configured max slots (default 10)
  SELECT COALESCE(max_active_providers_per_taluka_category, 10)
  INTO v_max_slots
  FROM site_settings
  WHERE id = 1;

  -- Calculate current active slots (active trials + active paid subscriptions)
  -- A listing with both active trial and scheduled paid sub counts as 1 slot!
  SELECT COUNT(DISTINCT vl.id)
  INTO v_active_count
  FROM vendor_listings vl
  JOIN vendors v ON v.id = vl.vendor_id
  WHERE vl.taluka_id = v_listing.taluka_id
    AND vl.category_id = v_listing.category_id
    AND vl.id != p_listing_id
    AND vl.approval_status = 'approved'
    AND vl.is_visible = true
    AND v.approval_status = 'approved'
    AND v.is_suspended = false
    AND (
      -- Condition A: Active Trial
      EXISTS (
        SELECT 1 FROM listing_trials lt
        WHERE lt.vendor_listing_id = vl.id
          AND lt.status = 'active'
          AND lt.starts_at <= NOW()
          AND lt.ends_at > NOW()
      )
      OR
      -- Condition B: Active Paid Subscription
      EXISTS (
        SELECT 1 FROM subscriptions s
        WHERE s.vendor_listing_id = vl.id
          AND s.status = 'active'
          AND s.starts_at <= NOW()
          AND s.ends_at > NOW()
      )
    );

  IF v_active_count >= v_max_slots THEN
    UPDATE vendor_listings
    SET approval_status = 'waitlisted', updated_at = NOW()
    WHERE id = p_listing_id;

    RETURN jsonb_build_object(
      'success', false,
      'error', 'SLOT_LIMIT_REACHED',
      'message', format('All %s slots are occupied. Listing placed in waiting list.', v_max_slots),
      'active_count', v_active_count,
      'max_slots', v_max_slots
    );
  END IF;

  -- Calculate 30-day IST trial period
  v_starts_at := COALESCE(p_start_date, NOW());
  v_ends_at := v_starts_at + INTERVAL '30 days';

  -- Create trial record
  INSERT INTO listing_trials (
    vendor_listing_id,
    starts_at,
    ends_at,
    status,
    is_override,
    override_reason,
    created_by
  ) VALUES (
    p_listing_id,
    v_starts_at,
    v_ends_at,
    'active',
    p_is_override,
    p_override_reason,
    p_admin_user_id
  ) RETURNING id INTO v_trial_id;

  -- Update listing to approved and visible
  UPDATE vendor_listings
  SET approval_status = 'approved',
      is_visible = true,
      approved_at = COALESCE(approved_at, NOW()),
      first_activated_at = COALESCE(first_activated_at, NOW()),
      updated_at = NOW()
  WHERE id = p_listing_id;

  RETURN jsonb_build_object(
    'success', true,
    'trial_id', v_trial_id,
    'starts_at', v_starts_at,
    'ends_at', v_ends_at,
    'active_count', v_active_count + 1,
    'max_slots', v_max_slots
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 7. Updated Stored Procedure: Activate Vendor Listing (Convert Trial to Paid or Direct Annual)
-- Handles:
-- a) If active trial exists: annual subscription starts at trial ends_at (keeps remaining free trial days!)
-- b) If trial expired: re-checks slot availability; if full, keeps/moves to waitlist
-- c) Converted trial within trial period counts as 1 slot, never 2
CREATE OR REPLACE FUNCTION activate_vendor_listing(
  p_listing_id UUID,
  p_amount NUMERIC,
  p_payment_method payment_method_enum,
  p_reference_number TEXT,
  p_notes TEXT,
  p_admin_user_id UUID,
  p_start_date TIMESTAMPTZ DEFAULT NULL,
  p_custom_end_date TIMESTAMPTZ DEFAULT NULL
)
RETURNS JSONB AS $$
DECLARE
  v_listing RECORD;
  v_max_slots INTEGER;
  v_active_count INTEGER;
  v_existing_sub RECORD;
  v_active_trial RECORD;
  v_starts_at TIMESTAMPTZ;
  v_ends_at TIMESTAMPTZ;
  v_new_sub_id UUID;
  v_payment_id UUID;
BEGIN
  -- Lock listing record
  SELECT vl.*, v.provider_name, v.business_name
  INTO v_listing
  FROM vendor_listings vl
  JOIN vendors v ON v.id = vl.vendor_id
  WHERE vl.id = p_listing_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Listing not found');
  END IF;

  SELECT COALESCE(max_active_providers_per_taluka_category, 10)
  INTO v_max_slots
  FROM site_settings
  WHERE id = 1;

  -- Check if this listing currently has an active trial
  SELECT * INTO v_active_trial
  FROM listing_trials
  WHERE vendor_listing_id = p_listing_id
    AND status = 'active'
    AND ends_at > NOW()
  ORDER BY ends_at DESC
  LIMIT 1;

  -- Count other active listings in this taluka + category (Condition A or B)
  SELECT COUNT(DISTINCT vl.id)
  INTO v_active_count
  FROM vendor_listings vl
  JOIN vendors v ON v.id = vl.vendor_id
  WHERE vl.taluka_id = v_listing.taluka_id
    AND vl.category_id = v_listing.category_id
    AND vl.id != p_listing_id
    AND vl.approval_status = 'approved'
    AND vl.is_visible = true
    AND v.approval_status = 'approved'
    AND v.is_suspended = false
    AND (
      EXISTS (
        SELECT 1 FROM listing_trials lt
        WHERE lt.vendor_listing_id = vl.id
          AND lt.status = 'active'
          AND lt.starts_at <= NOW()
          AND lt.ends_at > NOW()
      )
      OR
      EXISTS (
        SELECT 1 FROM subscriptions s
        WHERE s.vendor_listing_id = vl.id
          AND s.status = 'active'
          AND s.starts_at <= NOW()
          AND s.ends_at > NOW()
      )
    );

  -- If trial already expired or non-existent, re-check slot limit
  IF v_active_trial.id IS NULL AND v_active_count >= v_max_slots THEN
    UPDATE vendor_listings
    SET approval_status = 'waitlisted', updated_at = NOW()
    WHERE id = p_listing_id;

    RETURN jsonb_build_object(
      'success', false,
      'error', 'SLOT_LIMIT_REACHED',
      'message', format('Payment recorded but all %s slots are full. Placed on waiting list.', v_max_slots),
      'active_count', v_active_count,
      'max_slots', v_max_slots
    );
  END IF;

  -- Check for existing active subscription (Renewal)
  SELECT * INTO v_existing_sub
  FROM subscriptions
  WHERE vendor_listing_id = p_listing_id
    AND status = 'active'
    AND ends_at > NOW()
  ORDER BY ends_at DESC
  LIMIT 1;

  IF v_existing_sub.id IS NOT NULL THEN
    -- Extend from subscription expiry
    v_starts_at := v_existing_sub.ends_at;
    v_ends_at := COALESCE(p_custom_end_date, v_starts_at + INTERVAL '1 year');
  ELSIF v_active_trial.id IS NOT NULL THEN
    -- Extend seamlessly from trial end date! Provider keeps all remaining free days.
    v_starts_at := COALESCE(p_start_date, v_active_trial.ends_at);
    v_ends_at := COALESCE(p_custom_end_date, v_starts_at + INTERVAL '1 year');
  ELSE
    -- Brand new / expired: activate from specified start date (or now)
    v_starts_at := COALESCE(p_start_date, NOW());
    v_ends_at := COALESCE(p_custom_end_date, v_starts_at + INTERVAL '1 year');
  END IF;

  -- Create annual subscription
  INSERT INTO subscriptions (
    vendor_listing_id,
    amount,
    currency,
    starts_at,
    ends_at,
    status
  ) VALUES (
    p_listing_id,
    p_amount,
    'INR',
    v_starts_at,
    v_ends_at,
    'active'
  ) RETURNING id INTO v_new_sub_id;

  -- If converting an active trial, update trial status to converted
  IF v_active_trial.id IS NOT NULL THEN
    UPDATE listing_trials
    SET status = 'converted',
        converted_at = NOW(),
        converted_subscription_id = v_new_sub_id,
        updated_at = NOW()
    WHERE id = v_active_trial.id;
  END IF;

  -- Record payment receipt
  INSERT INTO payments (
    vendor_listing_id,
    vendor_id,
    subscription_id,
    amount,
    currency,
    payment_method,
    payment_date,
    reference_number,
    notes,
    recorded_by_user_id
  ) VALUES (
    p_listing_id,
    v_listing.vendor_id,
    v_new_sub_id,
    p_amount,
    'INR',
    p_payment_method,
    v_starts_at::DATE,
    p_reference_number,
    p_notes,
    p_admin_user_id
  ) RETURNING id INTO v_payment_id;

  -- Update listing to approved and visible
  UPDATE vendor_listings
  SET approval_status = 'approved',
      is_visible = true,
      approved_at = COALESCE(approved_at, NOW()),
      first_activated_at = COALESCE(first_activated_at, NOW()),
      updated_at = NOW()
  WHERE id = p_listing_id;

  RETURN jsonb_build_object(
    'success', true,
    'subscription_id', v_new_sub_id,
    'payment_id', v_payment_id,
    'trial_converted', (v_active_trial.id IS NOT NULL),
    'starts_at', v_starts_at,
    'ends_at', v_ends_at,
    'active_count', v_active_count + 1,
    'max_slots', v_max_slots
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 8. Updated Stored Procedure: Fetch Daily Rotated Providers
-- Incorporates Condition A (active trial) OR Condition B (active subscription)
-- Ensures trial vendors participate equally without priority or demotion.
CREATE OR REPLACE FUNCTION get_active_rotated_providers(
  p_taluka_id UUID,
  p_category_id UUID,
  p_target_timestamp TIMESTAMPTZ DEFAULT NOW()
)
RETURNS TABLE (
  listing_id UUID,
  vendor_id UUID,
  provider_name VARCHAR,
  business_name VARCHAR,
  slug VARCHAR,
  mobile VARCHAR,
  whatsapp_number VARCHAR,
  experience_years INTEGER,
  full_address TEXT,
  google_maps_url TEXT,
  latitude NUMERIC,
  longitude NUMERIC,
  profile_image_url TEXT,
  description_en TEXT,
  description_mr TEXT,
  is_verified BOOLEAN,
  first_activated_at TIMESTAMPTZ,
  display_order INTEGER
) AS $$
DECLARE
  v_count INTEGER;
  v_offset INTEGER;
  v_day_number INTEGER;
BEGIN
  -- Count eligible providers (Condition A or Condition B)
  SELECT COUNT(DISTINCT vl.id)
  INTO v_count
  FROM vendor_listings vl
  JOIN vendors v ON v.id = vl.vendor_id
  WHERE vl.taluka_id = p_taluka_id
    AND vl.category_id = p_category_id
    AND vl.approval_status = 'approved'
    AND vl.is_visible = true
    AND v.approval_status = 'approved'
    AND v.is_suspended = false
    AND v.is_publicly_visible = true
    AND (
      -- Condition A: Active Trial
      EXISTS (
        SELECT 1 FROM listing_trials lt
        WHERE lt.vendor_listing_id = vl.id
          AND lt.status = 'active'
          AND lt.starts_at <= p_target_timestamp
          AND lt.ends_at > p_target_timestamp
      )
      OR
      -- Condition B: Active Paid Subscription
      EXISTS (
        SELECT 1 FROM subscriptions s
        WHERE s.vendor_listing_id = vl.id
          AND s.status = 'active'
          AND s.starts_at <= p_target_timestamp
          AND s.ends_at > p_target_timestamp
      )
    );

  IF v_count = 0 THEN
    RETURN;
  END IF;

  -- Calculate deterministic IST day offset
  v_day_number := get_ist_day_offset(p_target_timestamp);
  v_offset := v_day_number % v_count;

  -- Return rotated providers
  RETURN QUERY
  WITH base_providers AS (
    SELECT
      vl.id AS b_listing_id,
      v.id AS b_vendor_id,
      v.provider_name AS b_provider_name,
      v.business_name AS b_business_name,
      v.slug AS b_slug,
      v.mobile AS b_mobile,
      v.whatsapp_number AS b_whatsapp_number,
      v.experience_years AS b_experience_years,
      v.full_address AS b_full_address,
      v.google_maps_url AS b_google_maps_url,
      v.latitude AS b_latitude,
      v.longitude AS b_longitude,
      v.profile_image_url AS b_profile_image_url,
      v.description_en AS b_description_en,
      v.description_mr AS b_description_mr,
      v.is_verified AS b_is_verified,
      vl.first_activated_at AS b_first_activated_at,
      ROW_NUMBER() OVER (ORDER BY vl.first_activated_at ASC, vl.id ASC) - 1 AS b_idx
    FROM vendor_listings vl
    JOIN vendors v ON v.id = vl.vendor_id
    WHERE vl.taluka_id = p_taluka_id
      AND vl.category_id = p_category_id
      AND vl.approval_status = 'approved'
      AND vl.is_visible = true
      AND v.approval_status = 'approved'
      AND v.is_suspended = false
      AND v.is_publicly_visible = true
      AND (
        EXISTS (
          SELECT 1 FROM listing_trials lt
          WHERE lt.vendor_listing_id = vl.id
            AND lt.status = 'active'
            AND lt.starts_at <= p_target_timestamp
            AND lt.ends_at > p_target_timestamp
        )
        OR
        EXISTS (
          SELECT 1 FROM subscriptions s
          WHERE s.vendor_listing_id = vl.id
            AND s.status = 'active'
            AND s.starts_at <= p_target_timestamp
            AND s.ends_at > p_target_timestamp
        )
      )
  )
  SELECT
    b_listing_id,
    b_vendor_id,
    b_provider_name,
    b_business_name,
    b_slug,
    b_mobile,
    b_whatsapp_number,
    b_experience_years,
    b_full_address,
    b_google_maps_url,
    b_latitude,
    b_longitude,
    b_profile_image_url,
    b_description_en,
    b_description_mr,
    b_is_verified,
    b_first_activated_at,
    ((b_idx - v_offset + v_count) % v_count)::INTEGER AS display_order
  FROM base_providers
  ORDER BY display_order ASC;
END;
$$ LANGUAGE plpgsql STABLE;
